Update add-user

diff --git a/bin/add-user b/bin/add-user
--- a/bin/add-user
+++ b/bin/add-user
@@ -4,8 +4,10 @@
 user=$1
 password=$2
 
-# Adding user
-/usr/sbin/useradd -m "$user" -s /bin/bash
-
-# Adding password
-echo "$user:$password" | /usr/sbin/chpasswd
+if [! -d "/home/$user" ]; then
+	/usr/sbin/useradd -m "$user" -s /bin/bash
+	echo "$user:$password" | /usr/sbin/chpasswd
+else
+	echo "Error: ${user} exist. Can not continue."
+	exit 1
+fi
