Update php-conf-build

diff --git a/bin/php-conf-build b/bin/php-conf-build
--- a/bin/php-conf-build
+++ b/bin/php-conf-build
@@ -1,45 +1,47 @@
 #!/bin/bash
 
 if [ "$(whoami)" != "root" ]; then
-	echo "You must be root to execute this script."
-	exit 1
+        echo "You must be root to execute this script."
+        exit 1
 fi
 
 user=$1
 version=$2
 
+[ $# -eq 0 ] && { echo "Usage: $0 user php.version"; exit 1; }
+
 if [ ! -d "/home/$user" ]; then
-	echo "Error: User ${user} does not exist."
-	exit 1
+        echo "Error: User ${user} does not exist."
+        exit 1
 fi
 
 template="/usr/local/brorsen/template/php/pool"
 output="/home/${user}/conf/php/${user}.conf"
 
 if [[ -f $output ]]; then
-	rm $output
+        rm $output
 fi
 
 if [ ! -d "/home/$user/conf/php" ]; then
-	mkdir /home/$user/conf/php
+        mkdir /home/$user/conf/php
 fi
 
 while IFS= read line; do
-	echo "${line}" |
-	sed "s|USER|${user}|g" >> $output
+        echo "${line}" |
+        sed "s|USER|${user}|g" >> $output
 done < $template
 
 if [[ -L "/etc/php/$version/fpm/pool.d/$user.conf" ]]; then
-	echo "Symlink already exist."
+        echo "Symlink already exist."
 else
-	rm -rf /etc/php/*/fpm/pool.d/$user.conf
-	ln -s /home/$user/conf/php/$user.conf /etc/php/$version/fpm/pool.d/$user.conf
+        rm -rf /etc/php/*/fpm/pool.d/$user.conf
+        ln -s /home/$user/conf/php/$user.conf /etc/php/$version/fpm/pool.d/$user.conf
 fi
 
 php$version-fpm -t 2>/dev/null > /dev/null
 if [[ $? == 0 ]]; then
-	service php$version-fpm reload
+        service php$version-fpm reload
 else
-	echo "Please check PHP${version}-FPM config."
-	exit 1
+        echo "Please check PHP${version}-FPM config."
+        exit 1
 fi
