Update vhost-conf-build

diff --git a/bin/vhost-conf-build b/bin/vhost-conf-build
--- a/bin/vhost-conf-build
+++ b/bin/vhost-conf-build
@@ -1,48 +1,50 @@
 #!/bin/bash
 
 if [ "$(whoami)" != "root" ]; then
-	echo "You must be root to execute this script."
-	exit 1
+        echo "You must be root to execute this script."
+        exit 1
 fi
 
 user=$1
 domain=$2
 
+[ $# -eq 0 ] && { echo "Usage: $0 user domain"; exit 1; }
+
 if [ ! -d "/home/$user" ]; then
-	echo "Error: User ${user} does not exist."
-	exit 1
+        echo "Error: User ${user} does not exist."
+        exit 1
 fi
 
 template="/usr/local/brorsen/template/nginx/vhost"
 output="/home/${user}/conf/nginx/${domain}.conf"
 
 if [[ -f $output ]]; then
-	rm $output
+        rm $output
 fi
 
 if [ ! -d "/home/$user/conf/nginx" ]; then
-	mkdir /home/$user/conf/nginx
+        mkdir /home/$user/conf/nginx
 fi
 
 if [ ! -d "/home/$user/public_html" ]; then
-	mkdir /home/$user/public_html
-	chown $user:$user /home/$user/public_html
+        mkdir /home/$user/public_html
+        chown $user:$user /home/$user/public_html
 fi
 
 while IFS= read line; do
-	echo "${line}" |
-	sed "s|DOMAIN|${domain}|g" |
-	sed "s|USER|${user}|g" >> $output
+        echo "${line}" |
+        sed "s|DOMAIN|${domain}|g" |
+        sed "s|USER|${user}|g" >> $output
 done < $template
 
 if [[ -L "/etc/nginx/sites-enabled/$domain.conf" ]]; then
-	echo "Symlink already exist."
+        echo "Symlink already exist."
 else
-	ln -s /home/$user/conf/nginx/$domain.conf /etc/nginx/sites-enabled/$domain.conf
+        ln -s /home/$user/conf/nginx/$domain.conf /etc/nginx/sites-enabled/$domain.conf
 fi
 
 if [ ! -d "/home/$user/conf/ssl" ]; then
-	mkdir /home/$user/conf/ssl
+        mkdir /home/$user/conf/ssl
 fi
 
 openssl req -new -x509 -days 365 -nodes \
@@ -52,8 +54,8 @@ openssl req -new -x509 -days 365 -nodes \
 
 /usr/sbin/nginx -t 2>/dev/null > /dev/null
 if [[ $? == 0 ]]; then
-	/etc/init.d/nginx reload
+        /etc/init.d/nginx reload
 else
-	echo "Please check NGINX config."
-	exit 1
+        echo "Please check NGINX config."
+        exit 1
 fi
